version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: website-undangan-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedding_online
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: website-undangan-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker_data/redis:/data
    restart: unless-stopped
